### ISSUE TITLE
Broken dependency tree

### ISSUE THREAD

**Issue by JstDust** [rickbergfalk/sqlpad#1071]
Dependency tree seems broken since: https://github.com/sqlpad/sqlpad/pull/1070/commits/d31ebc03514c5cae8772c869008f76f21d5561af

oidc no longer works and fails to lookup the openid configuration from the issuer weirdly attempting to access 127.0.0.1:443.

I tried going down the rabbit hole and here is what i found. 
- Basically a blame fest between libraries and node version 14. 
- it seems to originate somewhere in agent-base see https://github.com/panva/node-openid-client/issues/320 and https://github.com/sindresorhus/got/issues/1776 .

I tried fixing the versions for a few hours but it went from bad to worse. i opted to branch of my next change on a commit before the merge of #1070 and recommend reverting at-least the server dependency updates until someone can figure out what is happening with this agent-base dependency since there are multiple paths to the agent-base dependency.

**Comment by rickbergfalk** [comment]
@JstDust are you still experiencing an issue with this? I noticed openid-client has a new major version available https://github.com/panva/node-openid-client/releases/tag/v5.0.0 but I don't have any openid setup handy to test it out at the moment.

**Comment by mqueb** [comment]
hi, got the same issue. 

`2022-03-21T14:58:41.225-04:00 [APP/PROC/WEB/0] [OUT] {"level":50,"time":"2022-03-21T18:58:41.224Z","pid":15,"hostname":"037a1723-a6c2-472f-7a1e-4d8c","name":"sqlpad-app","err":{"type":"AggregateError","message":"Issuer.discover() failed.\n RequestError: connect ECONNREFUSED 127.0.0.1:443\n RequestError: connect ECONNREFUSED 127.0.0.1:443","stack":"AggregateError: Issuer.discover() failed.\n RequestError: connect ECONNREFUSED 127.0.0.1:443\n RequestError: connect ECONNREFUSED 127.0.0.1:443\n at Function.discover (/usr/app/node_modules/openid-client/lib/issuer.js:265:17)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async enableOidc (/usr/app/auth-strategies/oidc.js:78:20)\n at async authStrategies (/usr/app/auth-strategies/index.js:51:3)\n at async makeApp (/usr/app/app.js:177:3)\n at async startServer (/usr/app/server.js:185:15)","name":"AggregateError"},"msg":"Error starting SQLPad"}`

**Comment by brianmay** [comment]
What action is required to fix this bug?

**Comment by brianmay** [comment]
If I install nodejs version 16.9.1, run "npm update" in the server directory, this problem disappears. openid-client is still running the old version and is not updated in the process.
