### ISSUE TITLE
cannot download query result from crate connection

### ISSUE THREAD

**Issue by benbenqiang** [rickbergfalk/sqlpad#114]
crate 0.55.2 , sqlpad crashed when saving result as CVS or xlsx 
`http.js:733
      throw new TypeError('The header content contains invalid characters');
            ^
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at /usr/lib/node_modules/sqlpad/routes/download-results.js:47:25
    at newArguments.(anonymous function) (/usr/lib/node_modules/sqlpad/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/lib/node_modules/sqlpad/node_modules/nedb/lib/datastore.js:518:14)
    at callback (/usr/lib/node_modules/sqlpad/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/lib/node_modules/sqlpad/node_modules/nedb/lib/cursor.js:193:12
    at /usr/lib/node_modules/sqlpad/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/lib/node_modules/sqlpad/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /usr/lib/node_modules/sqlpad/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/lib/node_modules/sqlpad/node_modules/nedb/node_modules/async/lib/async.js:582:34)`

**Comment by rickbergfalk** [comment]
Hi @benbenqiang. Could I get the version of SqlPad and version of Node.js you are using? 

Are there any interesting characters in the query name? The only thing I could think of affecting the header content is the filename...

**Comment by benbenqiang** [comment]
Hi,  i use the latest version of sqlpad and version of node is  v0.10.46  
it seems following query string make sqlpad crash:
"sum(order_status/7) as cancel"

**Comment by rickbergfalk** [comment]
I'm not able to reproduce the issue on my instances of sqlpad - I'm wondering if your version of node is partially responsible as Node 0.10.46 is quite old. 

Is it possible for you to update to node 4.x.x? It is the current long term support release. Even better, the version 6.x.x is the current version and will become the new long term support release.

**Comment by benbenqiang** [comment]
Thanks,i got it
