### ISSUE TITLE
Google oauth token error

### ISSUE THREAD

**Issue by marcmillien** [rickbergfalk/sqlpad#121]
I'm currently running sqlpad as a private service and I was wanting to setup google oauth.

I setup the following envvars:
```
GOOGLE_CLIENT_SECRET=****
GOOGLE_CLIENT_ID=****
PUBLIC_URL=https://internalurl
DISABLE_USERPASS_AUTH=true
WHITELISTED_DOMAINS=our google services domain
```

I have create an oauth identifier in google console and activated the google+ API (just in case).

But I have the following error (I use the docker container tag 1.15.0).
```
TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:294:12)
    at Strategy.OAuth2Strategy._createOAuthError (/opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:341:16)
    at /opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/opt/node-v4.3.0-linux-x64/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9
```

Any idea? :).

Thanks.

**Comment by rickbergfalk** [comment]
Hi @marcmillien 

I'm not too experienced with OAuth setup but I've managed to get it working locally...

Have you specified the redirect URI in the google api console? Mine in testing is http://localhost/auth/google/callback. If the port is not standard http it must be provided, and if you are using a baseUrl, that'll need to be considered too. For example, http://localhost:8080/mybaseurl/auth/google/callback.

OAuth documentation is something I've been meaning to get to... 

Let me know if this helps or if you've already had that set up.

**Comment by rickbergfalk** [comment]
Were you able to get OAuth working @marcmillien?

**Comment by marcmillien** [comment]
Hi @rickbergfalk I admit I had no time to test it, I rolled back to the standard email method.
I'll give a try with the next version :). I close the issue for now.
