### ISSUE TITLE
Cannot update query created in v1 without first adding a tag.

### ISSUE THREAD

**Issue by dave-elkan** [rickbergfalk/sqlpad#154]
When updating a query I created, I found the following error in the logs:

```
{ ValidationError: child "tags" fails because ["tags" at position 0 fails because ["0" must be a string]]
    at Object.exports.process (sqlpad/node_modules/joi/lib/errors.js:154:19)
    at _validateWithOptions (sqlpad/node_modules/joi/lib/any.js:601:31)
    at root.validate (sqlpad/node_modules/joi/lib/index.js:105:23)
    at QuerySave [as save] (sqlpad/models/Query.js:56:23)
    at sqlpad/routes/queries.js:148:11
    at sqlpad/models/Query.js:101:12
    at newArguments.(anonymous function) (sqlpad/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (sqlpad/node_modules/nedb/lib/datastore.js:518:14)
    at callback (sqlpad/node_modules/nedb/lib/cursor.js:126:19)
    at sqlpad/node_modules/nedb/lib/cursor.js:193:12
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"0" must be a string',
       path: 'tags.0',
       type: 'string.base',
       context: [Object] } ],
  _object:
   Query {
     _id: 'pM2qrGxptUUvsqso',
     name: ‘Query name’,
     tags: [ null ],
     connectionId: 'Z3rtugCVItxwhrZf',
     queryText: ‘query name’,
     chartConfiguration: { chartType: 'line', fields: [Object] },
     createdDate: 2016-07-22T23:19:19.582Z,
     createdBy: ‘email’,
     modifiedDate: 2017-01-11T22:54:53.077Z,
     modifiedBy: ‘email’,
     lastAccessDate: 2017-01-11T22:54:53.077Z },
  annotate: [Function] }
```

Fix is to add a tag to the query and then save again.

**Comment by rickbergfalk** [comment]
Thanks for the report @dave-elkan - Out of curiosity was this query created in sqlpad v1?

I'm not able to reproduce this in a fresh v2 install. There was a lot of weirdness happening with the old tagging input though, and I know there was some junk data on the backend that went along with it.

I'll have to add some data cleansing for the tags to remove any null/non-string values.

**Comment by dave-elkan** [comment]
I think you're right there.

I just tried saving a query which I was definitely created in v1 and the error occurs. New queries do not exhibit this behaviour.
