### ISSUE TITLE
run sql error

### ISSUE THREAD

**Issue by Chen-tao** [rickbergfalk/sqlpad#184]
Every time I run sqlpad and input sql once or twice, the sqlpad process just crush suddenly, error info like :

```shell
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipher.final (crypto.js:158:26)
    at decipher (/usr/local/lib/node_modules/sqlpad/lib/decipher.js:9:76)
    at connections.map (/usr/local/lib/node_modules/sqlpad/routes/connections.js:39:29)
    at Array.map (native)
    at /usr/local/lib/node_modules/sqlpad/routes/connections.js:38:31
    at /usr/local/lib/node_modules/sqlpad/models/Connection.js:87:12
    at newArguments.(anonymous function) (/usr/local/lib/node_modules/sqlpad/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/local/lib/node_modules/sqlpad/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/usr/local/lib/node_modules/sqlpad/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/local/lib/node_modules/sqlpad/node_modules/nedb/lib/cursor.js:193:12
events.js:163
      throw er; // Unhandled 'error' event
      ^
```

**Comment by rickbergfalk** [comment]
Hi @Chen-tao - Could I get the version of Node.js and sqlpad you are using? 

Also - are you using the default passphrase or are you supplying your own?

**Comment by rickbergfalk** [comment]
I'm going to close this ticket for now - if this issue is still a problem feel free to comment here and I can reopen

**Comment by Chen-tao** [comment]
Thanks and excuse for a late response.
- The version of Node.js and sqlpad you are using?
```bash
sqlpad -v
SqlPad version 2.2.0-beta1
```
-  Using the default passphrase or are you supplying your own?
using the default (as my memory said)
```bash
$ cat ~/.sqlpadrc
{
  "_": [],
  "port": 58000,
  "passphrase": "secret-encryption-phrase",
  "save": true
}%
```
And for now, this issue still can be reproduction.

**Comment by rickbergfalk** [comment]
No worries - can you check which version of node and npm you are using? You can do this by running ```node -v``` and ```npm -v```
