### ISSUE TITLE
After saving a new connection, click `New Query` sqlpad returns error

### ISSUE THREAD

**Issue by ELSS-ZION** [rickbergfalk/sqlpad#227]
+ sqlpad version: 2.3.0
+ node version: v6.10.3
+ npm version: 3.10.10
+ platform:  Windows Server 2012 R2

``` bash
PS C:\Users\Administrator> sqlpad
Launching server WITHOUT SSL

Welcome to SQLPad!. Visit http://localhost:80 to get started
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unknown type: 0
    at Parser.parseTokens (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\tedious\lib\token\stream-parser.js:99:30)
    at Parser._transform (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\tedious\lib\token\stream-parser.js:72:14)
    at Parser.Transform._read (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\readable-stream\lib\_stream_transform.js:
182:10)
    at Parser.Transform._write (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\readable-stream\lib\_stream_transform.js
:170:83)
    at doWrite (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Parser.Writable.write (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\readable-stream\lib\_stream_writable.js:32
2:11)
    at Parser.addBuffer (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\tedious\lib\token\token-stream-parser.js:50:26)

    at Connection.sendDataToTokenStreamParser (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\tedious\lib\connection.js
:644:37)
    at Connection.data (C:\nvm\v6.10.3\node_modules\sqlpad\node_modules\tedious\lib\connection.js:1070:21)
```

**Comment by rickbergfalk** [comment]
Hi @ELSS-ZION - It looks like this is related to the SQL Server driver or connection setup.

Were you able to successfully test your connection prior to saving it?

**Comment by rickbergfalk** [comment]
I'm going to close this issue - let me know if you're still encountering this and we can reopen if so
