### ISSUE TITLE
update  connection error

### ISSUE THREAD

**Issue by WuQic** [rickbergfalk/sqlpad#317]
![image](https://user-images.githubusercontent.com/5144010/37018901-0e663270-2151-11e8-8f9c-554f69620103.png)

{ ValidationError: child "hanaport" fails because ["hanaport" is not allowed to be empty]
    at Object.exports.process (/opt/workspace/sqlpad/node_modules/joi/lib/errors.js:190:19)
    at internals.Object._validateWithOptions (/opt/workspace/sqlpad/node_modules/joi/lib/types/any/index.js:669:31)
    at module.exports.internals.Any.root.validate (/opt/workspace/sqlpad/node_modules/joi/lib/index.js:139:23)
    at ConnectionSave [as save] (/opt/workspace/sqlpad/server/models/Connection.js:84:23)
    at /opt/workspace/sqlpad/server/routes/connections.js:133:16
    at /opt/workspace/sqlpad/server/models/Connection.js:109:12
    at newArguments.(anonymous function) (/opt/workspace/sqlpad/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/workspace/sqlpad/node_modules/nedb/lib/datastore.js:518:14)
    at callback (/opt/workspace/sqlpad/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/workspace/sqlpad/node_modules/nedb/lib/cursor.js:193:12
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"hanaport" is not allowed to be empty',
       path: [Array],
       type: 'any.empty',
       context: [Object] } ],
  _object:
   Connection {
     _id: 'N9bw2sT2CDZi4p1F',
     name: 'xxx',
     driver: 'mysql',
     host: '192.168.0.212',
     port: '13307',

**Comment by rickbergfalk** [comment]
Sorry for the delay in response - I too ran into this error doing some refactoring. I will have it fixed in the next release over the next few days.

**Comment by rickbergfalk** [comment]
This should be fixed in version 2.5.2, now published. Let me know if you're still running into this after upgrade
