### ISSUE TITLE
sqlpad is not starting with forever or pm2

### ISSUE THREAD

**Issue by nagaraju02** [rickbergfalk/sqlpad#329]
I am able to run the sqlpad node process within sqlpad directory with this command - 

node server/server.js
forever start server/server.js

But the same is not working when I start the service from any other directory  and it throws error -

/root/.forever/quv-.log <==
    at Object.join (path.js:1236:7)
    at Object.<anonymous> (/var/www/sqlpad/server/lib/cli-flow.js:8:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error: Forever detected script exited with code: 1

**Comment by rickbergfalk** [comment]
Sorry I missed this @nagaraju02 - I'll see if I can reproduce this

**Comment by rickbergfalk** [comment]
I was unable to reproduce this on Mac OS. May I ask what version of node and operating system you running? 

I don't know that I'll be able to help much on this, but some things to try...

* Pull latest master
* Check node version installed. Node 6 should work but it might be good to update to node 8+ if possible
* rm -rf the node_modules directory, and do a fresh `npm install` for the dependencies

**Comment by rickbergfalk** [comment]
I'm going to close this issue for the time being - let me know if this is still and issue and we can reopen if needed

**Comment by nagaraju02** [comment]
Thanks!
