### ISSUE TITLE
Simple query causes crash (PG on RDS)

### ISSUE THREAD

**Issue by evan-burke** [rickbergfalk/sqlpad#383]
Sqlpad 2.7.1. 
Postgres 10.4 on RDS.  Seems to crash less if a 'limit 1000' is added to the query.

Query:

    select * from fake_complaint_rates;

Table structure:
```
CREATE TABLE "public"."fake_complaint_rates" (
  "complaint_rate" float8
);
```
Example data:

```
INSERT INTO "public"."fake_complaint_rates" VALUES (0.142220239778119);
INSERT INTO "public"."fake_complaint_rates" VALUES (0.032575241326039);
INSERT INTO "public"."fake_complaint_rates" VALUES (0.101116874108756);
INSERT INTO "public"."fake_complaint_rates" VALUES (0.0258135546366676);
INSERT INTO "public"."fake_complaint_rates" VALUES (0.125836686921209);
```

Debug output. Ran successfully with 'limit 1000' and 'limit 2000', crash on 'limit 3000'.
```
GET /api/schema-info/wlnOP0zanyyDfFaO 200 5.576 ms - 708
{"connectionName":"test","startTime":"2018-09-10T22:50:49.506Z","stopTime":"2018-09-10T22:50:50.224Z","queryRunTime":718,"rowCount":1000,"query":"select * from fake_complaint_rates\nlimit 1000"}
POST /api/query-result 200 781.426 ms - 37989
{"connectionName":"test","startTime":"2018-09-10T22:50:54.039Z","stopTime":"2018-09-10T22:50:54.738Z","queryRunTime":699,"rowCount":2000,"query":"select * from fake_complaint_rates\nlimit 2000"}
POST /api/query-result 200 774.988 ms - 75594
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.con.once (C:\Users\me\AppData\Roaming\npm\node_modules\sqlpad\node_modules\pg\lib\client.js:179:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Connection.emit (events.js:208:7)
    at Socket.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\sqlpad\node_modules\pg\lib\connection.js:76:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)
```

Full data including table creation DDL is here (360kb, ~5k rows) - 
http://delivio.net/fake_complaint_rates.sql

**Comment by rickbergfalk** [comment]
Hi @evan-burke  -- sorry for the late response to this. This might have something to do with the fact that SQLPad uses pg-cursor to enforce a query limit: https://github.com/brianc/node-pg-cursor

It could be something specific to RDS as well... Not sure how to go about debugging or testing this. 

If you wanted you could try forking sqlpad and changing the postgres implementation here: https://github.com/rickbergfalk/sqlpad/blob/master/server/drivers/postgres/index.js

Actually... as a quick hack of a test, you could try the following query. 2 SELECTs being executed will try a query again without pg-cursor

```sql
select * from fake_complaint_rates;
select * from fake_complaint_rates;
```

**Comment by evan-burke** [comment]
Thanks, I'll give it a shot.

**Comment by rickbergfalk** [comment]
Closing due to inactivity. If this is still an issue we can reopen.

**Comment by kidtronnix** [comment]
I just had this issue as well. Simple `select fake_col from real_table;` causes sqlpad to crash with pg connection.

Surely I can't be only one having such a basic issue for postgres? Make me think I'm missing something in config.

**Comment by kidtronnix** [comment]
I should clarify PG is on RDS too. Maybe that's why others aren't experiencing this.

**Comment by rickbergfalk** [comment]
@kidtronnix Is anything noteworthy being logged at all?

**Comment by lizmeister321** [comment]
I'm running into the same issue, data in PG running on a small EC2. Tried to run a "select * from table limit 400" causes server to fail; No logging showing system side at all.

**Comment by rickbergfalk** [comment]
Anyone willing to try things out now using v5? 

Hoping this is fixed now. v5 no longer uses the postgres streaming/cursor implementation for running queries, which I suspect was the culprit.

**Comment by rickbergfalk** [comment]
Going to close this out assuming v5 fixes things. If not let me know and can reopen.
