### ISSUE TITLE
Crash loop back on OpenShift

### ISSUE THREAD

**Issue by ridvan70** [rickbergfalk/sqlpad#389]
Hi,

the pod crashes at start on OpenShift with the error message:

`/usr/app/node_modules/mkdirp/index.js:90
                    throw err0
Error: EACCES: permission denied, mkdir '/var/lib/sqlpad/cache'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/usr/app/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/app/server/lib/db.js:7:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
at require (internal/module.js:11:18)`

Used Docker image sqlpad/sqlpad:latest

Regards
Ridvan

**Comment by ridvan70** [comment]
Following RUN in the Dockerfile solves the problem:
`RUN chmod -R 777 /var/lib/sqlpad`
