### ISSUE TITLE
Mysql DB 'ER_NOT_SUPPORTED_AUTH_MODE'

### ISSUE THREAD

**Issue by CrashLaker** [rickbergfalk/sqlpad#458]
Hi all.

How can I solve this?

```
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/usr/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/app/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/usr/app/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    --------------------
    at Protocol._enqueue (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/usr/app/node_modules/mysql/lib/Connection.js:119:18)
    at /usr/app/drivers/mysql/index.js:55:18
    at new Promise (<anonymous>)
    at runQuery (/usr/app/drivers/mysql/index.js:51:10)
    at Object.testConnection (/usr/app/drivers/mysql/index.js:119:10)
    at testConnection (/usr/app/drivers/index.js:170:17)
    at /usr/app/routes/test-connection.js:12:11
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol ' +
    'requested by server; consider upgrading MySQL ' +
    'client',
  sqlState: '08004',
  fatal: true
```

**Comment by rickbergfalk** [comment]
Not certain on what auth mode you are using, but I recall the mysql nodejs driver not supporting one of the newer protocols. It might now and the drive may need an update to accommodate this.

**Comment by CrashLaker** [comment]
Noticed that. Probably the new Mysql update came with new security features.

My Mysql DB version is  "5.5.60-MariaDB" which I'm connecting with no issues.

The other database is a "MySQL Community Server - GPL - Version 8.0.13" with a "caching_sha2_password" checkbox marked which I cannot unmark.

I'm even facing this error when trying to login from Mysql Workbench CE 6.3.9.
```
Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found
```

**Comment by rickbergfalk** [comment]
I imagine this will be an issue until this PR is merged https://github.com/mysqljs/mysql/pull/1962

**Comment by CrashLaker** [comment]
got this working from the solution here:
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'
```

Where root as your user localhost as your URL and password as your password
then `flush privileges;`

thank you
