### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by MuchAdoAboutNothing** [rickbergfalk/sqlpad#518]
We're getting the following exception when running a simple select count(*) query over UnixODBC. It seems to be a known limitation in Node (http://thecodebarbarian.com/an-overview-of-bigint-in-node-js.html).

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at stringify (/usr/app/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/usr/app/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/usr/app/node_modules/express/lib/response.js:158:21)
    at /usr/app/routes/query-result.js:61:16
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at JSON2CSVParser.processValue (/usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1319:22)
    at JSON2CSVParser.processCell (/usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1299:19)
    at /usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1277:23
    at Array.map (<anonymous>)
    at JSON2CSVParser.processRow (/usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1276:43)
    at /usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1508:23
    at Array.map (<anonymous>)
    at JSON2CSVParser.processData (/usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1507:30)
    at JSON2CSVParser.parse (/usr/app/node_modules/json2csv/dist/json2csv.cjs.js:1465:23)
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at resolve (/usr/app/models/resultCache.js:96:25)
    at new Promise (<anonymous>)
    at Object.writeJson (/usr/app/models/resultCache.js:94:10)
    at getQueryResult (/usr/app/routes/query-result.js:101:23)
```

**Comment by clach04** [comment]
Possibly solution https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510

**Comment by MuchAdoAboutNothing** [comment]
@rickbergfalk I have a potential fix for this using a fix described at http://thecodebarbarian.com/an-overview-of-bigint-in-node-js.html

BigInt.prototype.toJSON = function() { return this.toString(); };

**Comment by rickbergfalk** [comment]
Thanks @MuchAdoAboutNothing!

**Comment by JimNewaz** [comment]
**For String:**  

(BigInt.prototype as any).toJSON = function () {
    return String(this)
};

**For Number:**

(BigInt.prototype as any).toJSON = function () {
    return Number(this)
};
