### ISSUE TITLE
copy & paste doesn't work

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#649]
I experience it constantly on Windows 10. (I was using mysql2 but I'm not sure if this is related).

I think it's something to do with the way Windows encodes newlines maybe? 

1. Open winword
2. write in a text document (over two lines)
```
select
1
```
3. Copy these two lines and paste into sqlpad. Run query.

I get this message on the log, and the GUI is counting "Query time: ..." indefinitely.

So there are two problems here, one is the inability to parse the query, and the other, feedback not presented on GUI.

```
   2020-05-31T11:30:20.98+0300 [APP/PROC/WEB/0] OUT {"level":50,"time":"2020-05-31T08:30:20.980Z","pid":7,"hostname":"0c9fe0be-0e4e-45e8-4e32-98e9","name":"sqlpad-app","stack":"Error: invalid syntax at line 1 col 7:\n\n  Select\r\n        ^\n    at Lexer._token (/usr/app/node_modules/moo/moo.js:533:13)\n    at Lexer.next (/usr/app/node_modules/moo/moo.js:480:19)\n    at getStatements (/usr/app/node_modules/sql-limiter/src/get-statements.js:79:18)\n    at Object.apiGetStatements [as getStatements] (/usr/app/node_modules/sql-limiter/src/index.js:52:22)\n    at Batches.create (/usr/app/models/batches.js:48:8)\n    at create (/usr/app/routes/batches.js:36:41)\n    at /usr/app/lib/wrap.js:3:35\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)\n    at mustHaveConnectionAccess (/usr/app/middleware/must-have-connection-access.js:11:16)\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)\n    at mustBeAuthenticated (/usr/app/middleware/must-be-authenticated.js:5:12)\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)\n    at mustBeAuthenticated (/usr/app/middleware/must-be-authenticated.js:5:12)\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/app/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/app/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)","type":"Error","msg":"invalid syntax at line 1 col 7:\n\n  Select\r\n        ^"}
   2020-05-31T11:30:20.98+0300 [APP/PROC/WEB/0] OUT {"level":30,"time":"2020-05-31T08:30:20.981Z","pid":7,"hostname":"xxx","name":"sqlpad-web","req":{"id":187,"method":"POST","url":"/api/batches"},"res":{"statusCode":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/usr/app/node_modules/pino-http/logger.js:71:38)\n    at ServerResponse.emit (events.js:323:22)\n    at onFinish (_http_outgoing.js:730:10)\n    at onCorkedFinish (_stream_writable.js:721:5)\n    at afterWrite (_stream_writable.js:528:5)\n    at afterWriteTick (_stream_writable.js:515:10)\n    at processTicksAndRejections (internal/process/task_queues.js:83:21)"},"responseTime":5,"msg":"request errored"}
```

**Comment by eladeyal-intel** [comment]
Ahh cool workaround. If I hit shift-enter to "prettify" the query and then run, it works.

**Comment by rickbergfalk** [comment]
I'll look into this quick. It likely is the encoding for line endings which will need to be supported by the parser. Not having an error indication in the UI is unexpected as well.

**Comment by rickbergfalk** [comment]
This should be fixed in `latest`/master. If the SQL tokenizer fails to tokenize the query, the error is handled like a query error and displayed in the UI accordingly. 

The underlying library used to tokenize the SQL statement has also been fixed to support Windows line endings. https://github.com/rickbergfalk/sql-limiter

**Comment by eladeyal-intel** [comment]
works now :-)
