### ISSUE TITLE
backendDatabaseUri parameter isn't working 

### ISSUE THREAD

**Issue by smohan6** [rickbergfalk/sqlpad#742]
I am trying to isolate the database by using an AWS RDS instance. I have given the connection string as value backendDatabaseUri in config.ini file . But it seems like the app doesn't connect to the database.  Is there any other changes that I need to do for the app to connect to the external database.

**Comment by eladeyal-intel** [comment]
Can you attach the config file? Don't forget to hide usernames and passwords

**Comment by eladeyal-intel** [comment]
Also note it's not in latest release, only in "latest" (trunk)

**Comment by smohan6** [comment]
[config.txt](https://github.com/rickbergfalk/sqlpad/files/4842836/config.txt)

Please find attached config file.

**Comment by eladeyal-intel** [comment]
It's usually

backendDatabaseUri="mariadb://admin: password@hostname:3306/sqlpad?sslmode=require

**Comment by eladeyal-intel** [comment]
Also, maybe you need to unset dbPath

**Comment by rickbergfalk** [comment]
I think `dbPath` is still needed since it is used for session and query result storage. I'll probably be exploring allowing config to move that to backend datbase as well in #727

**Comment by smohan6** [comment]
@eladeyal-intel  I tried the connection string. I see that the app has started but there are some messages as below 

{"level":40,"time":"2020-06-29T13:56:34.735Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key allowedDomains in file /home/ec2-user/sqlpad/config-example.ini.","v":1}
{"level":40,"time":"2020-06-29T13:56:34.735Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPassphrase / CERT_PASSPHRASE. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md","v":1}
{"level":40,"time":"2020-06-29T13:56:34.735Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPath / CERT_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md","v":1}
{"level":40,"time":"2020-06-29T13:56:34.735Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key backendDatabaseUri in file /home/ec2-user/sqlpad/config-example.ini.","v":1}
{"level":40,"time":"2020-06-29T13:56:34.736Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key disableAuthDefaultRole in file /home/ec2-user/sqlpad/config-example.ini.","v":1}
{"level":40,"time":"2020-06-29T13:56:34.736Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: keyPath / KEY_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md","v":1}
{"level":40,"time":"2020-06-29T13:56:34.736Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key samlLinkHtml in file /home/ec2-user/sqlpad/config-example.ini.","v":1}
{"level":40,"time":"2020-06-29T13:56:34.736Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key samlAutoSignUp in file /home/ec2-user/sqlpad/config-example.ini.","v":1}
{"level":40,"time":"2020-06-29T13:56:34.736Z","pid":29918,"hostname":"ip-10-10-10-176.us-west-2.compute.internal","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key samlDefaultRole in file /home/ec2-user/sqlpad/config-example.ini.","v":1}

Also I don't see any connections in the Database. Am I missing something here.

**Comment by eladeyal-intel** [comment]
Are you sure you're using the correct version? `allowedDomains` and `backendDatabaseUri` are not in the latest release (v4.4.0) but are only on "trunk" (latest). If you're deploying from Docker, use the image `sqlpad/sqlpad:latest`.

**Comment by smohan6** [comment]
Sure. I'll try this today

**Comment by eladeyal-intel** [comment]
@smohan6 should work with v5.0.0

**Comment by smohan6** [comment]
@eladeyal-intel  Thank you for your response. I tried with v5.0.0.Unfortunately I'm still getting the same error and we have now keep the set up as is for now. but I am trying to add the connection details when the app starts by running a script.

**Comment by eladeyal-intel** [comment]
What you write is very surprising and maybe I can help out.
1.  Can you explain what exactly are you trying to achieve. 
2. How do you install sqlpad?
3. Also attach the log files and updated config files (don't forget to remove passwords).

**Comment by smohan6** [comment]
1. I am trying to use an RDS instance to keep all the connection and user details by using backendDatabaseUri parameter so that we the container hosting sqlpad restarts , the data will still be available and the app just connects to that DB.
2. I'm using docker to host this. 
3. Even though I'm passing the backenduri parameter .. I don't see that ihe app is making a connection with the RDS instance 

{"level":40,"time":"2020-07-06T17:50:36.983Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPassphrase / CERT_PASSPHRASE. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":40,"time":"2020-07-06T17:50:36.983Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPath / CERT_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":40,"time":"2020-07-06T17:50:36.983Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: keyPath / KEY_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading users"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading connections"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading connectionAccesses"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading queries"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading queryHistory"}
{"level":30,"time":"2020-07-06T17:50:36.993Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading cache"}
{"level":30,"time":"2020-07-06T17:50:37.206Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Running migrations"}
{"level":30,"time":"2020-07-06T17:50:37.219Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00100-query-acl-schema: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.233Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00100-query-acl-schema: migrated (0.014s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.235Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00110-query-acl-data: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.239Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00110-query-acl-data: migrated (0.004s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.241Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00120-query-acl-remove-old-constraint: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.250Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00120-query-acl-remove-old-constraint: migrated (0.009s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.252Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00121-query-acl-add-user-email: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.256Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00121-query-acl-add-user-email: migrated (0.004s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.257Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00122-query-acl-add-group-id: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.261Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00122-query-acl-add-group-id: migrated (0.003s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.263Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00123-query-acl-remove-user-id-not-null: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.270Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00123-query-acl-remove-user-id-not-null: migrated (0.007s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.272Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00124-query-acl-add-constraint-user-email-query: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.278Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00124-query-acl-add-constraint-user-email-query: migrated (0.006s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.280Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00125-query-acl-add-constraint-group-query: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.287Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00125-query-acl-add-constraint-group-query: migrated (0.007s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.289Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00126-query-acl-add-constraint-user-id-query: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.297Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00126-query-acl-add-constraint-user-id-query: migrated (0.008s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.298Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00127-query-acl-add-index-query-id: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.318Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00127-query-acl-add-index-query-id: migrated (0.020s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.321Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00128-query-acl-move-everyone-id-to-group: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.326Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00128-query-acl-move-everyone-id-to-group: migrated (0.004s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.327Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00129-service-tokens-schema: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.340Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00129-service-tokens-schema: migrated (0.012s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.342Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00200-nedb-sqlite-tables: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.372Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00200-nedb-sqlite-tables: migrated (0.030s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.374Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00210-nedb-to-sqlite-data: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.387Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00210-nedb-to-sqlite-data: migrated (0.013s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.389Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00300-batch-statements: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.401Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00300-batch-statements: migrated (0.012s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.402Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00400-query-history-to-batch: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.407Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00400-query-history-to-batch: migrated (0.005s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.409Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00500-redshift-spectrum-rename: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.411Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00500-redshift-spectrum-rename: migrated (0.002s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.413Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00600-password-reset-id-unique: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.417Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00600-password-reset-id-unique: migrated (0.004s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.419Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00700-fix-acl-unique-constraints: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.439Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00700-fix-acl-unique-constraints: migrated (0.020s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.442Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00800-user-disabled: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.448Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00800-user-disabled: migrated (0.006s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.450Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00900-query-user-id: migrating ======="}
{"level":30,"time":"2020-07-06T17:50:37.467Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"== 04-00900-query-user-id: migrated (0.017s)\n"}
{"level":30,"time":"2020-07-06T17:50:37.467Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Migration finished"}
{"level":30,"time":"2020-07-06T17:50:37.468Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading seed data from /Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server"}
{"level":30,"time":"2020-07-06T17:50:37.470Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Creating access on every connection to every user..."}
{"level":50,"time":"2020-07-06T17:50:37.487Z","pid":52688,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","errno":-2,"syscall":"stat","code":"ENOENT","path":"/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/public/favicon.ico","stack":"Error: ENOENT: no such file or directory, stat '/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/public/favicon.ico'\n    at Object.statSync (fs.js:1029:3)\n    at resolveSync (/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/node_modules/serve-favicon/index.js:187:17)\n    at favicon (/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/node_modules/serve-favicon/index.js:61:12)\n    at makeApp (/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/app.js:82:11)\n    at startServer (/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/server.js:162:21)","type":"Error","msg":"Error starting SQLPad"}

running it locally using the below command. 
node server.js --config ~/Desktop/v.5/sqlpad-5.0.0/config-example.ini 
[config (2).txt](https://github.com/rickbergfalk/sqlpad/files/4886916/config.2.txt)
Also tried the connection string given by you but it doesn't work as it errors out saying "host not recognized"

Let me know if I am missing anything here .

**Comment by rickbergfalk** [comment]
Realized I need to fix the loading seed data log message.

@smohan6 it looks like the UI isn't built. Did you run the build.sh script? https://github.com/rickbergfalk/sqlpad/blob/master/scripts/build.sh

I didn't realize thats there things error if the UI is not built. I'll see if I can add a friendlier message to build the UI.

All those migrating log messages indicate that it is connecting to some sort of database. Are you able to connect to that database and confirm that it had tables added to it?

**Comment by eladeyal-intel** [comment]
BTW You can change appLogLevel to debug and get more detailed information in the logs.

**Comment by smohan6** [comment]
@rickbergfalk  I ran build.sh script and now I am getting Access denied error. 

SanjayMhan11293:server sanjaymohan$ sudo node server.js --config ~/Desktop/v.5/sqlpad-5.0.0/config-example.ini 
{"level":40,"time":"2020-07-08T21:22:33.262Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPassphrase / CERT_PASSPHRASE. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":40,"time":"2020-07-08T21:22:33.263Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: certPath / CERT_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":40,"time":"2020-07-08T21:22:33.263Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"DEPRECATED CONFIG: keyPath / KEY_PATH. To be removed in v6. Delegate SSL to reverse proxy instead https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md"}
{"level":30,"time":"2020-07-08T21:22:33.273Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading users"}
{"level":30,"time":"2020-07-08T21:22:33.273Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading connections"}
{"level":30,"time":"2020-07-08T21:22:33.274Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading connectionAccesses"}
{"level":30,"time":"2020-07-08T21:22:33.274Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading queries"}
{"level":30,"time":"2020-07-08T21:22:33.274Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading queryHistory"}
{"level":30,"time":"2020-07-08T21:22:33.274Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","msg":"Loading cache"}
{"level":50,"time":"2020-07-08T21:22:33.416Z","pid":19873,"hostname":"ip-192-168-85-28.us-west-2.compute.internal","name":"sqlpad-app","name":"SequelizeAccessDeniedError","parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)"},"original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)\n    at ConnectionManager.connect (/Users/sanjaymohan/Desktop/v.5/sqlpad-5.0.0/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","msg":"Error starting SQLPad"}

I have added this in the config file 
backendDatabaseUri="mysql://root@localhost/sqlpad?password=<password>"
Also tried backendDatabaseUri="mysql://root:<password>@127.0.0.1/sqlpad".. but it didn't work  and I don't see any connections from app to the database.
