### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by sapisuper** [rickbergfalk/sqlpad#822]
Hi,

I just got this error :

```
{"level":50,"time":"2020-08-19T05:02:28.641Z","pid":1,"hostname":"sqlpad-b9bfdbdc8-dlckz","name":"sqlpad-app","message":"request entity too large","expected":244333,"length":244333,"limit":102400,"type":"entity.too.large","stack":"PayloadTooLargeError: request entity too large\n at readStream (/usr/app/node_modules/raw-body/index.js:155:17)\n at getRawBody (/usr/app/node_modules/raw-body/index.js:108:12)\n at read (/usr/app/node_modules/body-parser/lib/read.js:77:3)\n at jsonParser (/usr/app/node_modules/body-parser/lib/types/json.js:135:5)\n at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/usr/app/node_modules/express/lib/router/index.js:317:13)\n at /usr/app/node_modules/express/lib/router/index.js:284:7\n at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)\n at next (/usr/app/node_modules/express/lib/router/index.js:275:10)\n at favicon (/usr/app/node_modules/serve-favicon/index.js:68:7)\n at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/usr/app/node_modules/express/lib/router/index.js:317:13)\n at /usr/app/node_modules/express/lib/router/index.js:284:7\n at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)\n at next (/usr/app/node_modules/express/lib/router/index.js:275:10)\n at loggingMiddleware (/usr/app/node_modules/pino-http/logger.js:125:7)","msg":"request entity too large"}
```

When I'm doing insert a lot of data. it is  possible to increase limit body-parser? by default body-parser is 100kb following this message error
```request entity too large","expected":244333,"length":244333,"limit":102400```

Thanks,

Satria

**Comment by sapisuper** [comment]
Closed this issue.

Just missing configuration **ME_CONFIG_REQUEST_SIZE** 

Default value is 100kb , increase this value to avoid error PayloadTooLargeError: request entity too large.

Thanks,

Satria

**Comment by rickbergfalk** [comment]
Sorry I missed this @sapisuper. I'm not familiar with that env variable. If that solved your issue great! If not we may need to add a config entry for this in SQLPad as well.
