### ISSUE TITLE
Crashes when executing comments (queries start with --) Postgres

### ISSUE THREAD

**Issue by santoshsahoo** [rickbergfalk/sqlpad#88]
Here is the stacktrace.

Object [object Object] has no method 'handleEmptyQuery'

/usr/local/lib/node_modules/sqlpad/node_modules/pg/lib/client.js:118
      self.activeQuery.handleEmptyQuery(con);
                       ^
TypeError: Object [object Object] has no method 'handleEmptyQuery'
    at null.<anonymous> (/usr/local/lib/node_modules/sqlpad/node_modules/pg/lib/client.js:118:24)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/sqlpad/node_modules/pg/lib/connection.js:109:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

**Comment by rickbergfalk** [comment]
Determined this to be an issue with the pg cursor package. A pending pull request will fix the issue - https://github.com/brianc/node-pg-cursor/pull/17

**Comment by rickbergfalk** [comment]
this will be fixed next sqlpad publish

**Comment by rickbergfalk** [comment]
version 1.17.0 has been published to npm
